# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 07:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=200, verbose_name='URL')),
                ('designnumber', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Design')),
                ('clusters', models.FilePathField(blank=True, verbose_name='Clusters')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestartd1', models.DateTimeField(blank=True, verbose_name='Start time design 1')),
                ('timeendd1', models.DateTimeField(blank=True, verbose_name='End time design 1')),
                ('timedeltad1', models.DateTimeField(blank=True, verbose_name='Delta time design 1')),
                ('timestartd2', models.DateTimeField(blank=True, verbose_name='Start time design 2')),
                ('timeendd2', models.DateTimeField(blank=True, verbose_name='End time design 2')),
                ('timedeltad2', models.DateTimeField(blank=True, verbose_name='Delta time design 2')),
                ('timestartd3', models.DateTimeField(blank=True, verbose_name='Start time design 3')),
                ('timeendd3', models.DateTimeField(blank=True, verbose_name='End time design 3')),
                ('timedeltad3', models.DateTimeField(blank=True, verbose_name='Delta time design 3')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='User Identifier')),
                ('string', models.CharField(default='', max_length=200, verbose_name='String')),
                ('agerange', models.PositiveSmallIntegerField(default=0, verbose_name='Age Range')),
            ],
        ),
        migrations.AddField(
            model_name='stats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cluster.User'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cluster.User'),
        ),
    ]
